
import { Place, Category } from './types';
import data from '@/app/lib/placeholder-images.json';

const images = data.placeholderImages;

export const CATEGORIES: Category[] = [
  { id: '1', name: 'Atracciones', icon: 'FerrisWheel' },
  { id: '2', name: 'Restaurantes', icon: 'Utensils' },
  { id: '3', name: 'Hostales', icon: 'Hotel' },
  { id: '4', name: 'Piscinas', icon: 'Waves' },
  { id: '5', name: 'Spa', icon: 'Sparkles' },
  { id: '6', name: 'Información', icon: 'Info' },
];

export const PLACES: Place[] = [
  // XETULUL ATRACCIONES
  {
    id: 'pueblo-caribeno',
    name: 'Pueblo Caribeño',
    category: 'Atracciones',
    parque: 'Xetulul',
    zona: 'Inspirado en Izabal',
    loMejor: 'Nueva atracción, museo, restaurante, juego con agua',
    description: 'Espacio inspirado en el Castillo de San Felipe. Incluye un juego tipo barco donde puedes lanzar agua a otros usuarios mientras navegas obstáculos.',
    imageUrl: 'https://picsum.photos/seed/irtra-caribe/600/400',
    location: 'Km 180.5 carretera a Quetzaltenango',
    hours: 'Jueves 10:00-17:00 | Viernes a domingo 10:00-18:00',
    telefono: '7722-9450',
    rating: 4.8,
    reviewCount: 210,
    featured: true
  },
  {
    id: 'gondola-salpicona',
    name: 'Góndola Salpicona',
    category: 'Atracciones',
    parque: 'Xetulul',
    zona: 'Plaza Italia',
    loMejor: 'Juego con agua, alta velocidad',
    description: 'Juego en balsa con descensos rápidos, vistas del parque y recorrido lleno de adrenalina.',
    imageUrl: 'https://picsum.photos/seed/irtra-gondola/600/400',
    location: 'Plaza Italia',
    hours: 'Jueves 10:00-17:00 | Viernes a domingo 10:00-18:00',
    telefono: '7722-9450',
    rating: 4.9,
    reviewCount: 340,
    featured: true
  },
  {
    id: 'jurakan',
    name: 'Jurakán',
    category: 'Atracciones',
    parque: 'Xetulul',
    zona: 'Área Choconoy',
    loMejor: 'Juego extremo, alta velocidad',
    description: 'Plataforma que gira y se eleva de lado a lado generando una experiencia intensa.',
    imageUrl: 'https://picsum.photos/seed/irtra-jurakan/600/400',
    location: 'Frente a Choconoy',
    hours: 'Jueves 10:00-17:00 | Viernes a domingo 10:00-18:00',
    telefono: '7722-9450',
    rating: 4.7,
    reviewCount: 180
  },
  {
    id: 'club-de-aviacion',
    name: 'Club de Aviación',
    category: 'Atracciones',
    parque: 'Xetulul',
    zona: 'Área nueva',
    loMejor: 'Ideal para niños',
    description: 'Juegos mecánicos con temática de aviones, aptos para niños y adultos.',
    imageUrl: 'https://picsum.photos/seed/irtra-aviones/600/400',
    location: 'Área nueva',
    hours: 'Jueves 10:00-17:00 | Viernes a domingo 10:00-18:00',
    telefono: '7722-9450',
    rating: 4.5,
    reviewCount: 120
  },
  {
    id: 'estrugensen',
    name: 'Estrugensen',
    category: 'Atracciones',
    parque: 'Xetulul',
    zona: 'Plaza Alemana',
    loMejor: 'Alta adrenalina, gran altura',
    description: 'Juego que eleva y gira en el aire ofreciendo una experiencia extrema.',
    imageUrl: 'https://picsum.photos/seed/irtra-estrug/600/400',
    location: 'Plaza Alemana',
    hours: 'Jueves 10:00-17:00 | Viernes a domingo 10:00-18:00',
    telefono: '7722-9450',
    rating: 4.8,
    reviewCount: 260
  },
  {
    id: 'sillas-voladoras',
    name: 'Sillas Voladoras',
    category: 'Atracciones',
    parque: 'Xetulul',
    zona: 'Área central',
    loMejor: 'Familiar, vista panorámica',
    description: 'Juego suave con vista del parque, ideal para toda la familia.',
    imageUrl: 'https://picsum.photos/seed/irtra-sillas/600/400',
    location: 'Cerca del carrusel',
    hours: 'Jueves 10:00-17:00 | Viernes a domingo 10:00-18:00',
    telefono: '7722-9450',
    rating: 4.6,
    reviewCount: 150
  },

  // XOCOMIL ATRACCIONES
  {
    id: 'vuelta-del-jaguar',
    name: 'Vuelta del Jaguar',
    category: 'Atracciones',
    parque: 'Xocomil',
    zona: 'Área nueva',
    loMejor: 'Extremo, caída vertical',
    description: 'Tobogán con cápsula que se abre y genera caída libre.',
    imageUrl: 'https://picsum.photos/seed/irtra-jaguar/600/400',
    location: 'Cerca de Tamagás',
    hours: 'Jueves a domingo 09:00-17:00',
    telefono: '7722-9400',
    rating: 4.9,
    reviewCount: 390,
    featured: true
  },
  {
    id: 'el-caracol',
    name: 'El Caracol',
    category: 'Atracciones',
    parque: 'Xocomil',
    zona: 'Área nueva',
    loMejor: 'Giro circular, adrenalina',
    description: 'Tobogán que gira en espiral antes de caer en piscina.',
    imageUrl: 'https://picsum.photos/seed/irtra-caracol/600/400',
    location: 'Área nueva',
    hours: 'Jueves a domingo 09:00-17:00',
    telefono: '7722-9400',
    rating: 4.7,
    reviewCount: 200
  },
  {
    id: 'el-regreson',
    name: 'El Regresón',
    category: 'Atracciones',
    parque: 'Xocomil',
    zona: 'Área nueva',
    loMejor: 'Alta velocidad, efecto rebote',
    description: 'Tobogán que impulsa hacia arriba y regresa con velocidad.',
    imageUrl: 'https://picsum.photos/seed/irtra-regreson/600/400',
    location: 'Área nueva',
    hours: 'Jueves a domingo 09:00-17:00',
    telefono: '7722-9400',
    rating: 4.8,
    reviewCount: 230
  },
  {
    id: 'tamagas',
    name: 'Tamagás',
    category: 'Atracciones',
    parque: 'Xocomil',
    zona: 'Área nueva',
    loMejor: 'Montaña rusa acuática',
    description: 'Tobogán con subidas, bajadas y curvas a gran altura.',
    imageUrl: 'https://picsum.photos/seed/irtra-tamagas/600/400',
    location: 'Área nueva',
    hours: 'Jueves a domingo 09:00-17:00',
    telefono: '7722-9400',
    rating: 4.9,
    reviewCount: 410,
    featured: true
  },
  {
    id: 'rapidos-de-xocomil',
    name: 'Rápidos de Xocomil',
    category: 'Atracciones',
    parque: 'Xocomil',
    zona: 'Área nueva',
    loMejor: 'Tobogán alto, adrenalina',
    description: 'Uno de los toboganes más altos de Centroamérica.',
    imageUrl: 'https://picsum.photos/seed/irtra-rapidos/600/400',
    location: 'Área nueva',
    hours: 'Jueves a domingo 09:00-17:00',
    telefono: '7722-9400',
    rating: 4.8,
    reviewCount: 300
  },
  {
    id: 'nido-de-serpientes',
    name: 'Nido de Serpientes',
    category: 'Atracciones',
    parque: 'Xocomil',
    zona: 'Área central',
    loMejor: '7 toboganes, variedad',
    description: 'Toboganes abiertos y cerrados con diferentes velocidades.',
    imageUrl: 'https://picsum.photos/seed/irtra-nido/600/400',
    location: 'Xocomil',
    hours: 'Jueves a domingo 09:00-17:00',
    telefono: '7722-9400',
    rating: 4.7,
    reviewCount: 250
  },

  // OTROS (ADAPTADOS)
  {
    id: 'los-corozos',
    name: 'Los Corozos',
    category: 'Restaurantes',
    parque: 'Hostales',
    loMejor: 'Ambiente relajante y buffet',
    description: 'Espacio con ambiente relajante, opciones de comida y acceso a servicios de descanso.',
    imageUrl: images.find(i => i.id === 'restaurant-corozos')?.imageUrl || '',
    location: 'Zona de servicios y bienestar, Hostales',
    hours: '8:00 a.m. – 8:00 p.m.',
    telefono: '7722-9450',
    rating: 4.8,
    reviewCount: 156
  },
  {
    id: 'hostales-san-martin',
    name: 'Hostales San Martín',
    category: 'Hostales',
    parque: 'Hostales',
    description: 'Complejo de hospedaje familiar con acceso a áreas verdes y servicios de descanso.',
    imageUrl: images.find(i => i.id === 'hostal-sanmartin')?.imageUrl || '',
    location: 'Área de hostales, complejo IRTRA',
    hours: '24 horas',
    telefono: '7722-9450',
    rating: 4.9,
    reviewCount: 320
  }
];
