
import { Place, Category } from './types';
import data from '@/app/lib/placeholder-images.json';

const images = data.placeholderImages;

export const CATEGORIES: Category[] = [
  { id: '1', name: 'Atracciones', icon: 'FerrisWheel' },
  { id: '2', name: 'Restaurantes', icon: 'Utensils' },
  { id: '3', name: 'Hostales', icon: 'Hotel' },
  { id: '4', name: 'Piscinas', icon: 'Waves' },
  { id: '5', name: 'Spa', icon: 'Sparkles' },
  { id: '7', name: 'Baños', icon: 'Bath' },
  { id: '6', name: 'Información', icon: 'Info' },
];

export const PLACES: Place[] = [
  // XETULUL ATRACCIONES
  {
    id: 'pueblo-fantasma',
    name: 'Pueblo Fantasma',
    category: 'Atracciones',
    parque: 'Xetulul',
    zona: 'Plaza Alemana',
    loMejor: 'Misterio y aventura familiar',
    description: 'Una de las atracciones más icónicas de Xetulul donde recorrerás un pueblo lleno de misterios y sorpresas visuales.',
    imageUrl: '/img/Pueblo-Fantasma1-885x500.jpg',
    location: 'Plaza Alemana, Xetulul',
    hours: 'Jueves 10:00-17:00 | Viernes a domingo 10:00-18:00',
    telefono: '7722-9450',
    rating: 4.8,
    reviewCount: 312,
    featured: true,
    intensity: 'Baja',
    targetAudience: 'Familiar',
    capacityPerTurn: 12,
    durationMinutes: 10,
    peopleInQueue: 24
  },
  {
    id: 'gondola-salpicona',
    name: 'Góndola Salpicona',
    category: 'Atracciones',
    parque: 'Xetulul',
    zona: 'Plaza Italia',
    loMejor: 'Juego con agua, alta velocidad',
    description: 'Juego en balsa con descensos rápidos, vistas del parque y recorrido lleno de adrenalina.',
    imageUrl: '/img/Gondola-Salpicona1-885x500.jpg',
    location: 'Plaza Italia',
    hours: 'Jueves 10:00-17:00 | Viernes a domingo 10:00-18:00',
    telefono: '7722-9450',
    rating: 4.9,
    reviewCount: 340,
    featured: true,
    intensity: 'Alta',
    targetAudience: 'Jóvenes y adultos',
    restrictions: 'Estatura mínima 1.20m',
    capacityPerTurn: 20,
    durationMinutes: 5,
    peopleInQueue: 120
  },
  {
    id: 'jurakan',
    name: 'Jurakán',
    category: 'Atracciones',
    parque: 'Xetulul',
    zona: 'Área Choconoy',
    loMejor: 'Juego extremo, alta velocidad',
    description: 'Plataforma que gira y se eleva de lado a lado generando una experiencia intensa.',
    imageUrl: '/img/Jurakan-885x500.jpg',
    location: 'Frente a Choconoy',
    hours: 'Jueves 10:00-17:00 | Viernes a domingo 10:00-18:00',
    telefono: '7722-9450',
    rating: 4.7,
    reviewCount: 180,
    intensity: 'Extrema',
    targetAudience: 'Buscadores de adrenalina',
    restrictions: 'Estatura mínima 1.40m',
    capacityPerTurn: 40,
    durationMinutes: 3,
    peopleInQueue: 150
  },
  {
    id: 'tamagas',
    name: 'Tamagás',
    category: 'Atracciones',
    parque: 'Xocomil',
    zona: 'Área nueva',
    loMejor: 'Montaña rusa acuática',
    description: 'Tobogán con subidas, bajadas y curvas a gran altura.',
    imageUrl: '/img/el-tamagas-2.jpg',
    location: 'Área nueva',
    hours: 'Jueves a domingo 09:00-17:00',
    telefono: '7722-9400',
    rating: 4.9,
    reviewCount: 410,
    featured: true,
    intensity: 'Alta',
    targetAudience: 'Familiar',
    restrictions: 'Estatura mínima 1.20m',
    capacityPerTurn: 2,
    durationMinutes: 4,
    peopleInQueue: 18
  },
  {
    id: 'pueblo-caribeno',
    name: 'Pueblo Caribeño',
    category: 'Atracciones',
    parque: 'Xetulul',
    zona: 'Inspirado en Izabal',
    loMejor: 'Nueva atracción, museo, restaurante, juego con agua',
    description: 'Espacio inspirado en el Castillo de San Felipe. Incluye un juego tipo barco donde puedes lanzar agua a otros usuarios mientras navegas obstáculos.',
    imageUrl: 'https://picsum.photos/seed/irtra-caribe/600/400',
    location: 'Km 180.5 carretera a Quetzaltenango',
    hours: 'Jueves 10:00-17:00 | Viernes a domingo 10:00-18:00',
    telefono: '7722-9450',
    rating: 4.8,
    reviewCount: 210,
    featured: false,
    intensity: 'Media',
    targetAudience: 'Todo público',
    restrictions: 'Estatura mínima 1.10m',
    capacityPerTurn: 16,
    durationMinutes: 8,
    peopleInQueue: 32
  },

  // RESTAURANTES
  {
    id: 'los-corozos',
    name: 'Los Corozos',
    category: 'Restaurantes',
    parque: 'Hostales',
    loMejor: 'Ambiente relajante y buffet',
    description: 'Espacio con ambiente relajante, opciones de comida y acceso a servicios de descanso.',
    imageUrl: images.find(i => i.id === 'restaurant-corozos')?.imageUrl || '',
    location: 'Zona de servicios y bienestar, Hostales',
    hours: '8:00 a.m. – 8:00 p.m.',
    telefono: '7722-9450',
    rating: 4.8,
    reviewCount: 156,
    cuisineType: 'Internacional / Buffet',
    serviceType: 'Mesa / Buffet'
  },
  
  // BAÑOS
  {
    id: 'banos-plaza-italia',
    name: 'Servicios Plaza Italia',
    category: 'Baños',
    parque: 'Xetulul',
    zona: 'Plaza Italia',
    description: 'Baños públicos con altos estándares de limpieza y mantenimiento.',
    imageUrl: 'https://picsum.photos/seed/irtra-restroom1/600/400',
    location: 'A un costado de Góndola Salpicona',
    hours: '10:00 a.m. – 6:00 p.m.',
    rating: 4.5,
    reviewCount: 45,
    accessibility: 'Totalmente accesible',
    availability: 'Alta'
  }
];
